sync with main
commit 520a71356c5767cfba5a133e788826680d70377d
Author: Gerit Wagner <gerit.wagner@uni-bamberg.de>
Date:   Sat Sep 28 16:28:13 2024 +0200

    fixes

commit 227bf715ae4c39b88d4fceb20353d6cac3787c7a
Author: Gerit Wagner <gerit.wagner@uni-bamberg.de>
Date:   Sat Sep 28 16:21:47 2024 +0200

    record.change_entrytype(): run_quality_model() with set_prepared=True

commit ba6ba8be481266c12cb6d0551ad08e4ea34b98ce
Author: Gerit Wagner <gerit.wagner@uni-bamberg.de>
Date:   Sat Sep 28 16:19:14 2024 +0200

    record.remove_field_provenance_note(): also remove IGNORE:note

commit 9f1c22814d5d34bfa7cf03b90b39d71e961ec597
Author: Gerit Wagner <gerit.wagner@uni-bamberg.de>
Date:   Sat Sep 28 16:18:37 2024 +0200

    no name-format defect for abbreviated names

commit 8df75d4dc2f846eda85ce4589b4a0388cacde0f0
Author: Gerit Wagner <gerit.wagner@uni-bamberg.de>
Date:   Sat Sep 28 16:18:02 2024 +0200

    fix long line

commit bbe831ddbc141da318c2c356a2f4b1ff61a31825
Author: Gerit Wagner <gerit.wagner@uni-bamberg.de>
Date:   Sat Sep 28 16:17:47 2024 +0200

    update validation

commit 12beaf5fdd4d874bc798d229896498850060da5a
Author: Gerit Wagner <gerit.wagner@uni-bamberg.de>
Date:   Sat Sep 28 16:03:27 2024 +0200

    update sync

    Signed-off-by: Gerit Wagner <gerit.wagner@uni-bamberg.de>

commit 520192c39ea21904d828fa6c4d863a5859c1a2d9
Author: Gerit Wagner <gerit.wagner@uni-bamberg.de>
Date:   Sat Sep 28 16:01:14 2024 +0200

    update set_prepared in record.run_quality_model()

commit ae108e57f14be0d20c4a275b40ed470457b1e262
Author: Gerit Wagner <gerit.wagner@uni-bamberg.de>
Date:   Sat Sep 28 16:00:42 2024 +0200

    crossref: raise ServiceNotAvailableException in crossref_query()

commit 9d882f338fb47a9fb200b98130c6504b46ef7709
Author: Gerit Wagner <gerit.wagner@uni-bamberg.de>
Date:   Sat Sep 28 15:58:17 2024 +0200

    prep polish: reset original state

commit ddea08ff0f0ffe79a2b40e560548f5ea9d1709c3
Author: pre-commit-ci[bot] <66853113+pre-commit-ci[bot]@users.noreply.github.com>
Date:   Tue Sep 24 06:16:49 2024 +0200

    [pre-commit.ci] pre-commit autoupdate (#556)

    updates:
    - [github.com/astral-sh/ruff-pre-commit: v0.6.2 → v0.6.7](https://github.com/astral-sh/ruff-pre-commit/compare/v0.6.2...v0.6.7)

    Co-authored-by: pre-commit-ci[bot] <66853113+pre-commit-ci[bot]@users.noreply.github.com>

commit 77c055e610f179fc76a0006f5ad11391d979111b
Author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
Date:   Tue Sep 24 06:16:39 2024 +0200

    update dependencies (#553)

    Co-authored-by: Poetry updater <actions@users.noreply.github.com>

commit d045a1da20b5dac6562aac34668c58666fb90e5b
Author: Gerit Wagner <gerit.wagner@uni-bamberg.de>
Date:   Mon Sep 23 08:35:53 2024 +0200

    fixes

commit a112c204f219ad180f2471126fd685efa0f66a6d
Author: Carlo <carlo_tang@web.de>
Date:   Fri Sep 20 07:38:10 2024 +0200

    add command how to verify git credentials

commit 81ebfb4c6c2202191b28c9bb590dbf79509d30f8
Author: Gerit Wagner <gerit.wagner@uni-bamberg.de>
Date:   Thu Sep 19 19:25:34 2024 +0200

    move packages asciinema to comments

commit 700c80508455046f2407aa493b36ba2760ccbed1
Author: Gerit Wagner <gerit.wagner@uni-bamberg.de>
Date:   Thu Sep 19 07:50:11 2024 +0200

    testing/fixes

commit 260566119990226e07a1485bbead1c73900560a8
Author: Gerit Wagner <gerit.wagner@uni-bamberg.de>
Date:   Thu Sep 19 06:21:49 2024 +0200

    tei_parser: set defaults

commit cd4214116c90e70c369edb38eb3a2e8999a97b29
Author: Gerit Wagner <gerit.wagner@uni-bamberg.de>
Date:   Mon Sep 16 11:24:19 2024 +0200

    upgrade: fix path-names in registry

commit 36bfd051989681c992b4743963df1a5053924884
Author: Gerit Wagner <gerit.wagner@uni-bamberg.de>
Date:   Mon Sep 16 11:08:04 2024 +0200

    cli: add instructions

commit ecbad8fc09c548ff1e9507269b6bc09a2ce26769
Author: Gerit Wagner <gerit.wagner@uni-bamberg.de>
Date:   Sun Sep 15 10:51:48 2024 +0200

    docs: add note on search udpates

commit aa1b6766a03a02151c4838422995bc7fe2581374
Author: Gerit Wagner <gerit.wagner@uni-bamberg.de>
Date:   Sat Sep 14 12:00:44 2024 +0200

    docs: drop asciinema of package --init

    Signed-off-by:t Gerit Wagner <gerit.wagner@uni-bamberg.de>

commit e791cc50bc8fd25ef209e3bef77342f31efe4e6f
Author: Gerit Wagner <gerit.wagner@uni-bamberg.de>
Date:   Sat Sep 14 09:41:21 2024 +0200

    crossref: update printout

commit ffd96287d953fd440dc26380ea3117ad32ce47ee
Author: Gerit Wagner <geritwagner@users.noreply.github.com>
Date:   Fri Sep 13 14:02:14 2024 +0200

    Reduce dependencies and switch to pydantic (#551)

    * move dependencies to arxiv and dedupe

    * pin numpy<2.0

    * add bib-dedupe

    * switch to pydantic

    * switch to pydantic

    * update

    * sources. use relative filenames

    * update docs

    * fix mypy

commit 1b84a37edd4767c96d46f17e765aa1d98a99a9d8
Author: Gerit Wagner <gerit.wagner@uni-bamberg.de>
Date:   Fri Sep 13 10:13:18 2024 +0200

    do not build paper in silent mode

commit 910dffac5f95df8e02b0efaf11c0a017de306f78
Author: Gerit Wagner <gerit.wagner@uni-bamberg.de>
Date:   Fri Sep 13 08:05:21 2024 +0200

    add todo

commit 7277c719f08c49274724ceb0f4af0b14c906f189
Author: Gerit Wagner <gerit.wagner@uni-bamberg.de>
Date:   Fri Sep 13 08:05:10 2024 +0200

    fix import error: local_index.builder

commit 026df759a150167b472fdd554683b8b491eb8105
Author: Gerit Wagner <gerit.wagner@uni-bamberg.de>
Date:   Wed Sep 11 07:09:15 2024 +0200

    paper_md: stop container

commit dc6ed4676acaf5a17eb9f5e8024a0ab848ae455a
Author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
Date:   Wed Sep 11 06:19:15 2024 +0200

    update dependencies (#550)

    Co-authored-by: Poetry updater <actions@users.noreply.github.com>

commit a4d12eccffc938a5c91ab117cf35e24120f45965
Author: Gerit Wagner <gerit.wagner@uni-bamberg.de>
Date:   Tue Sep 10 20:40:56 2024 +0200

    package_manager: packages do not necessarily start with "colrev."

commit 5d23d210d85c3ff0e16ae274d28690f0019e87d1
Author: Gerit Wagner <gerit.wagner@uni-bamberg.de>
Date:   Tue Sep 10 14:36:08 2024 +0200

    docker tests: remove intermediate containers

commit 5142f4db641252e2bd667752cf3a9d7ae54e7cfa
Author: Gerit Wagner <gerit.wagner@uni-bamberg.de>
Date:   Tue Sep 10 14:09:21 2024 +0200

    docs: update path

commit 2d6c2c28bcb803b7777adc0be79e41e665af05fe
Author: Gerit Wagner <gerit.wagner@uni-bamberg.de>
Date:   Tue Sep 10 14:08:34 2024 +0200

    fix docker test

commit 8c8f1370abf2dcbb5ab659c658f4411d46250425
Author: Gerit Wagner <gerit.wagner@uni-bamberg.de>
Date:   Tue Sep 10 13:42:36 2024 +0200

    docs: fix path

commit 7b8c31ed98f2b8e104b5f6e942e90f951160b280
Author: Gerit Wagner <geritwagner@users.noreply.github.com>
Date:   Tue Sep 10 09:23:19 2024 +0200

    colrev project installation (making internal packages optional) (#530)

    * colrev project installation / make internal packages optional

    * drop optional extras from colrev

    * update

    * update gh-workflow

    Signed-off-by: Gerit Wagner <gerit.wagner@uni-bamberg.de>

    * format and docs

    * update upgrade

    * extract colrev-internal-package discovery

    * [pre-commit.ci] auto fixes from pre-commit.com hooks

    for more information, see https://pre-commit.ci

    * install packages after --add and init

    * add note on colrev install . to docs

    ---------

    Signed-off-by: Gerit Wagner <gerit.wagner@uni-bamberg.de>
    Co-authored-by: pre-commit-ci[bot] <66853113+pre-commit-ci[bot]@users.noreply.github.com>

commit bea78ac507f362feb3b6126d01342a0d7f61ebec
Author: Julian Prester <julianprester@users.noreply.github.com>
Date:   Tue Sep 10 16:42:30 2024 +1000

    Use posix paths for platform independence (#544)

    * Convert all paths for docker to posix

    * PRISMA: as_posix()

    * [pre-commit.ci] auto fixes from pre-commit.com hooks

    for more information, see https://pre-commit.ci

    * OCRMyPDF: as_posix()

    * fix prisma: path unlink()

    ---------

    Co-authored-by: Julian Prester <hi@julianprester.com>
    Co-authored-by: Gerit Wagner <geritwagner@users.noreply.github.com>
    Co-authored-by: pre-commit-ci[bot] <66853113+pre-commit-ci[bot]@users.noreply.github.com>
    Co-authored-by: Gerit Wagner <gerit.wagner@uni-bamberg.de>

commit cd944e1db31a4365a225672f7b082be95db5efef
Author: Gerit Wagner <gerit.wagner@uni-bamberg.de>
Date:   Mon Sep 9 09:19:49 2024 +0200

    europe_pmc: catch ValueError in lock.release()

commit 685260be988edbb47d725cbfac298075ab46e011
Author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
Date:   Sun Sep 8 14:44:24 2024 +0200

    Update documentation (#548)

    * Update documentation

    * [pre-commit.ci] auto fixes from pre-commit.com hooks

    for more information, see https://pre-commit.ci

    ---------

    Co-authored-by: github-actions <github-actions@github.com>
    Co-authored-by: pre-commit-ci[bot] <66853113+pre-commit-ci[bot]@users.noreply.github.com>

commit 046c09ae0ff7f9a8f910e90a03c5585295797469
Author: Gerit Wagner <gerit.wagner@uni-bamberg.de>
Date:   Sun Sep 8 09:52:40 2024 +0200

    Run Update documentation weekly to avoid many PRs

commit 8fcb7e347ba1e29f26785d682e5c346be91a5237
Author: Gerit Wagner <gerit.wagner@uni-bamberg.de>
Date:   Sun Sep 8 09:52:15 2024 +0200

    refactor: pylint messages

commit 3ea50f6a377989081a06752a5a76492763385975
Author: Gerit Wagner <gerit.wagner@uni-bamberg.de>
Date:   Sun Sep 8 09:21:37 2024 +0200

    crossref: catch Exception

commit 163b5e10d88399fa88998ac04d63578e37dd51e3
Author: Gerit Wagner <geritwagner@users.noreply.github.com>
Date:   Sun Sep 8 09:19:55 2024 +0200

    Update README.md

commit 8f2460eb54e931d82d6b680107f05fd7736ff5a1
Author: Gerit Wagner <gerit.wagner@uni-bamberg.de>
Date:   Sun Sep 8 09:12:58 2024 +0200

    update and rename workflows

    Signed-off-by: Gerit Wagner <gerit.wagner@uni-bamberg.de>

commit c8bafc81c457e6007d33eb85635998eceec534bf
Author: Gerit Wagner <gerit.wagner@uni-bamberg.de>
Date:   Fri Sep 6 08:26:07 2024 +0200

    data endpoint. add and commit

commit b460db7230858c9cced3592e7d8c2ed759e437ec
Author: Gerit Wagner <gerit.wagner@uni-bamberg.de>
Date:   Fri Sep 6 08:25:48 2024 +0200

    init: check Docker available

commit 85ea667aa9571a118ef6688e86a78e64d77f0641
Author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
Date:   Wed Sep 4 08:58:41 2024 +0200

    update dependencies (#539)

    Co-authored-by: Poetry updater <actions@users.noreply.github.com>

commit 69d3eff5daf2df1a37816fc062eae73e6c11eecd
Author: Gerit Wagner <gerit.wagner@uni-bamberg.de>
Date:   Wed Sep 4 07:41:42 2024 +0200

    update relink_pdfs

    Signed-off-by: Gerit Wagner <gerit.wagner@uni-bamberg.de>

commit fbd4d780c275fbdf04e409a3d7f0c70843f400e2
Author: Gerit Wagner <gerit.wagner@uni-bamberg.de>
Date:   Tue Sep 3 09:11:58 2024 +0200

    add note on the order of pre/screening packages

commit 09aa2173829f03b177c60f38b76acf4fcc5d8649
Author: Gerit Wagner <gerit.wagner@uni-bamberg.de>
Date:   Tue Sep 3 08:20:41 2024 +0200

    update pdf text extraction

commit 6588b6867806312c24bb3bfd7d6eb0fc80860747
Author: Gerit Wagner <gerit.wagner@uni-bamberg.de>
Date:   Mon Sep 2 18:26:21 2024 +0200

    europe_pmc: refactor

commit 9877da003ef1085b4222c1d17bc0d364a00161c2
Author: Gerit Wagner <gerit.wagner@uni-bamberg.de>
Date:   Mon Sep 2 18:25:31 2024 +0200

    crossref: refactor

commit 7ba35df3e0ecfe204b3c639fd062e086a06e080d
Author: Gerit Wagner <gerit.wagner@uni-bamberg.de>
Date:   Mon Sep 2 18:24:35 2024 +0200

    update print output

commit dad30adb357ac0f38c171d1a5b9997e3a275e576
Author: Gerit Wagner <gerit.wagner@uni-bamberg.de>
Date:   Mon Sep 2 18:24:05 2024 +0200

    RecordNotInIndexException: ID mandatory

commit 45deaa89b222308c093505af150a392b97868db7
Author: Gerit Wagner <gerit.wagner@uni-bamberg.de>
Date:   Mon Sep 2 18:22:44 2024 +0200

    pdf-get: fix symlinks after renamed dirs

commit 91d5552929b026d1cd6fb0fe9bf11bf716b8a698
Author: Gerit Wagner <gerit.wagner@uni-bamberg.de>
Date:   Mon Sep 2 18:22:25 2024 +0200

    load: warn on non-standardized fields (instead of raising exception)

commit 829e036c061b1fc2903785500387924894525ff4
Author: Gerit Wagner <gerit.wagner@uni-bamberg.de>
Date:   Mon Sep 2 18:20:57 2024 +0200

    paper_md: fix path

commit 5b4079e6cc0a66877a0f82c15d9683a65632423e
Author: Gerit Wagner <gerit.wagner@uni-bamberg.de>
Date:   Sat Aug 31 18:59:57 2024 +0200

    sort SearchTypes

commit 84d7901208ed067e40443f2ec55bfd5a3a712a8f
Author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
Date:   Sat Aug 31 16:20:02 2024 +0200

    Update documentation (#528)

    Co-authored-by: github-actions <github-actions@github.com>